apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: spark-apps
  name: spark-app-role
rules:
- apiGroups: ["sparkoperator.k8s.io"]
  resources: ["sparkapplications"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-app-rolebinding
  namespace: spark-apps
subjects:
- kind: ServiceAccount
  name: spark-airflow
  namespace: spark-apps
roleRef:
  kind: Role
  name: spark-app-role
  apiGroup: rbac.authorization.k8s.io
