apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: read-parquet
  namespace: spark-apps  # Change to your namespace
spec:
  type: Python  # Specify Python for Python applications
  mode: cluster
  image: "rboubaya/spark:4.1"
  imagePullPolicy: Always
  mainApplicationFile: local:///app/read_parquet3.py  # Path to your Python script
  sparkVersion: "3.5.1"
  driver:
    cores: 1
    memory: "512m"
    serviceAccount: airflow  # Ensure this service account exists
    labels:
      version: "3.5.1"
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.5.1
  
 
