
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  namespace: efk
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd-role
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluentd-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluentd-role
subjects:
- kind: ServiceAccount
  name: fluentd
  namespace: efk
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: efk
spec:
  selector:
    matchLabels:
      name: fluentd
  template:
    metadata:
      labels:
        name: fluentd
    spec:
      nodeSelector:
        kubernetes.io/hostname: workers-vm-1
      tolerations:
      - key: "worker"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      serviceAccountName: fluentd
      containers:
        - name: fluentd
          image: fluent/fluentd-kubernetes-daemonset:v1.17-debian-elasticsearch8-1
          env:
            - name: FLUENTD_ARGS
              value: "--no-supervisor -q"
          volumeMounts:
            - name: config-volume
              mountPath: /fluentd/etc
            - name: airflow-logs
              mountPath: /usr/local/airflow/logs
            - name: varlog
              mountPath: /var/log
      volumes:
        - name: config-volume
          configMap:
            name: fluentd-config
        - name: airflow-logs
          hostPath:
            path: /usr/local/airflow/logs
        - name: varlog
          hostPath:
            path: /var/log
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: efk
data:
  fluent.conf: |
    <source>
      @id airflow-logs
      @type tail
      path /usr/local/airflow/logs/**/*.log
      pos_file /var/log/fluentd/airflow-logs.pos
      tag airflow.*
      <parse>
        @type none
      </parse>
    </source>

    <filter **>
      @type kubernetes_metadata
    </filter>

    <match **>
      @type elasticsearch
      @id out_es
      host elasticsearch.efk.svc.cluster.local
      port 9200
      scheme http
      logstash_format true
      logstash_prefix fluentd
      logstash_dateformat %Y.%m.%d
      include_tag_key true
      type_name access_log
      tag_key @log_name
      user fluentd
      password ${FLUENTD_PASSWORD}
      flush_interval 10s
    </match>

