apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags-pv2
spec:
  capacity:
    storage: 5Gi  # Adjust the size as needed
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    path: /mnt/nfs_share/airflow-dags  # Path on the NFS server
    server: 10.0.3.5  # NFS server's private IP address
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags-pvc
  namespace: airflow
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi  # Ensure this matches the PV capacity
  storageClassName: nfs-storage
  volumeName: airflow-dags-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-logs-pv
spec:
  capacity:
    storage: 5Gi  # Adjust the size as needed
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    path: /mnt/nfs_share/airflow-logs  # Path on the NFS server
    server: 10.0.3.5  # NFS server's private IP address
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs-pvc
  namespace: airflow
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi  # Ensure this matches the PV capacity
  storageClassName: nfs-storage
  volumeName: airflow-logs-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-postgresql-pv
spec:
  capacity:
    storage: 5Gi  # Ensure this matches the PVC capacity
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    path: /mnt/nfs_share/airflow-postgresql  # Path on the NFS server
    server: 10.0.3.5  # NFS server's private IP address
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-airflow-postgresql-0
  namespace: airflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Ensure this matches the PV capacity
  storageClassName: nfs-storage
  volumeName: airflow-postgresql-pv