apiVersion: v1
kind: Pod
metadata:
  labels:
    app: airflow-worker
spec:
  containers:
  - name: base
    image: rboubaya/airflow:1.0
    volumeMounts:
    - name: airflow-dags
      mountPath: /opt/airflow/dags
  volumes:
  - name: airflow-dags
    persistentVolumeClaim:
      claimName: airflow-dags-pvc
